### ISSUE TITLE
Honor 8 pro

### ISSUE THREAD

**Issue by ragavendranbala** [thestr4ng3r/arcore-patch#1]
I'm using Honor 8 pro (DUK-L09) I tried to install arcore preview 2 apk from Google website it get installed .. but when I tried to open helloAR apk it force closes automatically. I tried modified helloar but no luck and. I tried to modify arcore preview 2 by your method but I failed to modify it.

Can you please modify the Arcore preview 2 for my honor8pro (DUK-L09) device ID 1011. And give link for the modified apk and also give link to download helloAr... Thanks in advance

**Comment by thestr4ng3r** [comment]
Sorry, I do not provide any pre-built apks. Please give some more info about what exactly is failing then I can maybe help you.

**Comment by ragavendranbala** [comment]
i signed the preview2 apk for 1011 but now i don't know which helloar app have to be install. i have to build the official one or the sample apk which you given on previous post?

thanks in advance

**Comment by thestr4ng3r** [comment]
So just for clarification: You did run the `patch-apk.sh` script and installed `arcore-preview2-patched-signed.apk` successfully?

What do you mean by "the sample apk which you given on previous post"? Where did I give a sample apk?

HelloAR ist just a sample from Google, it has nothing to do with this project directly. If you want to try it, just clone https://github.com/google-ar/arcore-android-sdk and open the `samples/hello_ar_java` directory in Android Studio. Here are some instructions: https://developers.google.com/ar/develop/java/getting-started. Just make sure not to run an old version for Preview 1. The current master in that repo is the correct version.

But don't get your hopes up. As mentioned in the README, I haven't tested it on any of the devices in the list.

**Comment by ragavendranbala** [comment]
Thanks for your Reply... I installed HelloAr app from Google ... But now.. there is Focus issue with the camera.. is there is any ways to adjust the Focus of the camera? I'm using unity 2017.3

**Comment by thestr4ng3r** [comment]
Not that I knew. You're pretty much as far as you can get at the moment.
