### ISSUE TITLE
Conversion from device type string to device type number

### ISSUE THREAD

**Issue by lorizisback** [thestr4ng3r/arcore-patch#2]
Hi, 
would you kindly go a little further in detail about how to get a Device Type number starting from you proposed Device Type Strings list?

Thanks

**Comment by thestr4ng3r** [comment]
Sorry, I don't think I get your question. Let's say you have a Nexus 6P. The codename for that is Angler (see https://en.wikipedia.org/wiki/Nexus_6P). Then you just use the device type for kAngler in the list, which is 1006. Or what exactly are you asking?

**Comment by lorizisback** [comment]
Thanks for answering.

Let's say I'd like to get the id for Device Type String "kHero2lte".
In your script (very useful btw!) an integer representing the device is needed: how do i calculate such ID from the Device Type Strings list?

**Comment by thestr4ng3r** [comment]
Ah so you mean from the https://github.com/thestr4ng3r/arcore-patch/blob/master/device_type_strings.txt file if the value is not in the readme already? That can be done by reversing the `device_provider::ToString(const device_provider::DeviceType &)` function.

IIRC it is pretty big and uses a combination of regular conditional branches and jump tables, so it is relatively hard to manually find out the values. For the example values in the readme, I basically just brute-forced it by writing a script that patches the apk with different values, executes it on my phone and checks the outcome.
A more elegant solution would be to use symbolic execution or ESIL emulation for example. Maybe retdec could also be useful. That wasn't available yet when I worked on arcore the last time.

**Comment by lorizisback** [comment]
Ok thanks!
