### ISSUE TITLE
Patch expected to work with ARCore 1.0/1.1 final?

### ISSUE THREAD

**Issue by oscarbg** [thestr4ng3r/arcore-patch#5]

**Comment by yochananmarqos** [comment]
FYI, ARCore 1.1 supports more devices including my 6P:

> angler : Huawei Nexus 6P
> HWEML : Huawei P20
> HWCLT : Huawei P20 Pro
> HWNEO : Huawei Porsche Design Mate (previously identified as NEO-AL00)
> nash : Moto Z2 Force
> polaris : Xiaomi MIMIX 2S
> a7y17: Samsung Galaxy A7 (2017)
> a5y17 : Samsung Galaxy A5 (2017)
> SC-02K, SC-03K, SCV38, SCV39, starq, star2q : Galaxy S9 and S9+

Source: [Android Police](https://www.androidpolice.com/2018/03/27/arcore-v1-1-suggests-upcoming-support-galaxy-s9-s9-huawei-p20-p20-pro-nexus-6p-several-apk-teardown/)

**Comment by oscarbg** [comment]
ok changing title as I have Xiaomi Mi 5..

**Comment by thestr4ng3r** [comment]
No, this patch is currently only for Preview 2. I have not touched the final versions yet.
